### ISSUE TITLE
没有运行起来，感觉不靠谱

### ISSUE THREAD

**Issue by zhj12388** [aliyun/logstash-output-oss#4]
logstash 7.4.0
logstash-output-oss 0.1.2

[2020-12-21T19:31:43,494][INFO ][logstash.outputs.oss     ] Using version 0.1.x output plugin 'oss'. This plugin isn't well supported by the community and likely has no maintainer.
[2020-12-21T19:31:43,498][ERROR][logstash.outputs.oss     ] Unknown setting '"bucket"' for oss
[2020-12-21T19:31:43,498][ERROR][logstash.outputs.oss     ] Unknown setting '"access_key_secret"' for oss
[2020-12-21T19:31:43,498][ERROR][logstash.outputs.oss     ] Unknown setting '"encoding"' for oss
[2020-12-21T19:31:43,498][ERROR][logstash.outputs.oss     ] Unknown setting '"access_key_id"' for oss
[2020-12-21T19:31:43,498][ERROR][logstash.outputs.oss     ] Unknown setting '"endpoint"' for oss
[2020-12-21T19:31:43,503][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (ConfigurationError) Something is wrong with your configuration.", :backtrace=>["org.logstash.config.ir.CompiledPipeline.<init>(CompiledPipeline.java:100)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:60)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1156)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1143)", "org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39)", "opt.elk.logstash_minus_test.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$initialize$0(/opt/elk/logstash-test/logstash-core/lib/logstash/java_pipeline.rb:26)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)", "org.jruby.RubyClass.newInstance(RubyClass.java:915)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)", "opt.elk.logstash_minus_test.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/opt/elk/logstash-test/logstash-core/lib/logstash/pipeline_action/create.rb:36)", "opt.elk.logstash_minus_test.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/opt/elk/logstash-test/logstash-core/lib/logstash/pipeline_action/create.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:183)", "opt.elk.logstash_minus_test.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/opt/elk/logstash-test/logstash-core/lib/logstash/agent.rb:326)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:136)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:77)", "org.jruby.runtime.Block.call(Block.java:129)", "org.jruby.RubyProc.call(RubyProc.java:295)", "org.jruby.RubyProc.call(RubyProc.java:274)", "org.jruby.RubyProc.call(RubyProc.java:270)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.lang.Thread.run(Thread.java:748)"]}
warning: thread "Converge PipelineAction::Create<main>" terminated with exception (report_on_exception is true):
LogStash::Error: Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`
          create at org/logstash/execution/ConvergeResultExt.java:109
             add at org/logstash/execution/ConvergeResultExt.java:37
  converge_state at /opt/elk/logstash-test/logstash-core/lib/logstash/agent.rb:339
[2020-12-21T19:31:43,511][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`", :backtrace=>["org/logstash/execution/ConvergeResultExt.java:109:in `create'", "org/logstash/execution/ConvergeResultExt.java:37:in `add'", "/opt/elk/logstash-test/logstash-core/lib/logstash/agent.rb:339:in `block in converge_state'"]}
[2020-12-21T19:31:43,536][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::JavaLang::IllegalStateException` for `PipelineAction::Create<main>`>, :backtrace=>["org/logstash/execution/ConvergeResultExt.java:109:in `create'", "org/logstash/execution/ConvergeResultExt.java:37:in `add'", "/opt/elk/logstash-test/logstash-core/lib/logstash/agent.rb:339:in `block in converge_state'"]}

**Comment by wujinhu** [comment]
“:message=>"Unable to configure plugins: (ConfigurationError) Something is wrong with your configuration."”
请对比一下配置看看？

**Comment by bushidonggua** [comment]
[2022-05-12T12:01:12,878][ERROR][logstash.outputs.oss ] Unknown setting '"bucket"' for oss
[2022-05-12T12:01:12,957][ERROR][logstash.outputs.oss ] Unknown setting '"prefix"' for oss
[2022-05-12T12:01:12,957][ERROR][logstash.outputs.oss ] Unknown setting '"encoding"' for oss
[2022-05-12T12:01:12,957][ERROR][logstash.outputs.oss ] Unknown setting '"access_key_id"' for oss
[2022-05-12T12:01:12,958][ERROR][logstash.outputs.oss ] Unknown setting '"recover"' for oss
[2022-05-12T12:01:12,958][ERROR][logstash.outputs.oss ] Unknown setting '"endpoint"' for oss
[2022-05-12T12:01:12,958][ERROR][logstash.outputs.oss ] Unknown setting '"rotation_strategy"' for oss
[2022-05-12T12:01:12,958][ERROR][logstash.outputs.oss ] Unknown setting '"access_key_secret"' for oss
[2022-05-12T12:01:12,959][ERROR][logstash.outputs.oss ] Unknown setting '"size_rotate"' for oss
[2022-05-12T12:01:12,959][ERROR][logstash.outputs.oss ] Unknown setting '"additional_oss_settings"' for oss
[2022-05-12T12:01:12,959][ERROR][logstash.outputs.oss ] Unknown setting '"time_rotate"' for oss
[2022-05-12T12:01:12,977][ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:accesslog2oss, :exception=>"Java::JavaLang::IllegalStateException", :message=>"Unable to configure plugins: (ConfigurationError) Something is wrong with your

**Comment by bushidonggua** [comment]
同报错

**Comment by bushidonggua** [comment]
https://help.aliyun.com/document_detail/143440.html  用阿里云官网的配置配的

**Comment by bushidonggua** [comment]
@wujinhu 能帮忙看下吗？是不支持logstash 7.4.2吗？安装插件方式：./bin/logstash-plugin install logstash-output-oss
